# Generated by Django 5.1.3 on 2024-11-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subject',
            field=models.CharField(choices=[('korean', '국어'), ('english', '영어'), ('math', '수학'), ('history', '한국사'), ('social', '사회 탐구'), ('science', '과학 탐구')], default='korean', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='school',
            field=models.CharField(choices=[('middle', '중학교'), ('high', '고등학교')], default='middle', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년')], default='1', max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
